# Generated by Django 4.0.4 on 2022-04-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
