# Generated by Django 4.0.4 on 2022-04-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
